spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:h2:mem:ikitep}
    username: ${JDBC_DATABASE_USERNAME:mars}
    password: ${JDBC_DATABASE_PASSWORD:753}
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
